"""New Migration

Revision ID: ba82f0872164
Revises: e032b17da741
Create Date: 2024-04-02 22:49:35.189554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba82f0872164'
down_revision: Union[str, None] = 'e032b17da741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audience', sa.Column('frame_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audience', 'frame', ['frame_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audience', type_='foreignkey')
    op.drop_column('audience', 'frame_id')
    # ### end Alembic commands ###
