"""New Migration

Revision ID: cc53ff6cb882
Revises: f0a2f4fb7d89
Create Date: 2024-04-02 22:45:37.706725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc53ff6cb882'
down_revision: Union[str, None] = 'f0a2f4fb7d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
