"""New Migration

Revision ID: d9f889b11dfd
Revises: e4a7cacb3bcc
Create Date: 2024-05-23 16:10:02.657923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f889b11dfd'
down_revision: Union[str, None] = 'e4a7cacb3bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('data', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
