"""New Migration

Revision ID: e4a7cacb3bcc
Revises: bc179e294ff9
Create Date: 2024-05-11 14:16:06.918124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a7cacb3bcc'
down_revision: Union[str, None] = 'bc179e294ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path to studetns files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_path to studetns files_id'), 'path to studetns files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_path to studetns files_id'), table_name='path to studetns files')
    op.drop_table('path to studetns files')
    # ### end Alembic commands ###
